const  translation_En_Ar = {" Switch to Agency View ":"التبديل إلى عرض الوكالة", 
"Search":"يبحث", 
" Quick Actions ":"إجراءات سريعة", 
"Add a Contact":"أضف جهة اتصال", 
"Add a new Contact from scratch":"أضف جهة اتصال جديدة من الصفر", 
"Book an Appointment":"حجز موعد", 
"Book a new appointment in calendar":"حجز موعد جديد في التقويم", 
"Send a Review Request":"إرسال طلب مراجعة", 
"Send a review request to the customer":"أرسل طلب مراجعة إلى العميل", 
"Create an Opportunity":"خلق فرصة", 
"Create new qualified opportunity":"إنشاء فرصة جديدة مؤهلة", 
" Launchpad ":"Launchpad", 
" Dashboard ":"لوحة القيادة", 
" Conversations ":"المحادثات", 
" Calendars ":"التقويمات", 
" Contacts ":"جهات الاتصال", 
" Opportunities ":"فرص", 
" Payments ":"المدفوعات", 
" Marketing ":"تسويق", 
" Automation ":"الأتمتة", 
" Sites ":"المواقع", 
" Memberships ":"عضوية", 
" Media Storage ":"تخزين الوسائط", 
" Reputation ":"سمعة", 
" Reporting ":"الإبلاغ", 
" App Marketplace ":"سوق التطبيق", 
" Mobile App ":"تطبيق الجوال", 
" Whatsapp ":"Whatsapp", 
" book ":"كتاب", 
" Settings ":"إعدادات", 
"Schedule appointment":"جدول موعد", 
" Close ":"يغلق", 
" Save ":"يحفظ", 
" unknown ":"مجهول", 
"View Changelog":"عرض changelog", 
"Notifications":"إشعارات", 
"Support":"يدعم", 
"Login As ":"تسجيل الدخول", 
"Signout":"توقيع", 
" Manual Actions ":"الإجراءات اليدوية", 
" Templates (Snippets) ":"قوالب (مقتطفات)", 
" Trigger Links ":"روابط الزناد", 
" Links ":"الروابط", 
" Analyze ":"تحليل", 
" You have one or more failed payments. Please check your billing history. ":"لديك مدفوعات واحدة أو أكثر.يرجى التحقق من سجل الفواتير الخاص بك.", 
"Ignore":"يتجاهل", 
"More Info":"مزيد من المعلومات", 
"Unread":"غير مقروء", 
"Recents":"شروط", 
"Starred":"لعب دور البطولة", 
"All":"الجميع", 
"Quick Filters":"مرشحات سريعة", 
" Clear Filters ":"مرشحات واضحة", 
"Assigned (Contact Owner)":"تم تعيينه (مالك الاتصال)", 
"My Chat":"محادثتي", 
"Assigned To":"تعيين ل", 
"Unassigned":"غير معروف", 
"Last Message Direction ":"اتجاه الرسالة الأخير", 
"Inbound":"واردة", 
"Outbound":"خارج", 
"Last Outbound Message Type":"آخر نوع الرسالة الصادرة", 
"Manual":"يدوي", 
"Automated":"آلي", 
"Last Message Channel":"آخر قناة الرسائل", 
"Email":"بريد إلكتروني", 
"SMS":"رسالة قصيرة", 
"GBP":"GBP", 
"Live Chat":"دردشة حية", 
"Whatsapp":"Whatsapp", 
"Facebook":"فيسبوك", 
"Calls":"المكالمات", 
"Voicemail":"البريد الصوتي", 
"Instagram":"Instagram", 
" Cancel ":"يلغي", 
" Apply ":"يتقدم", 
" 31 RESULTS ":"31 نتيجة", 
" Latest-All ":"آخر الكل", 
" Latest - All messages":"أحدث - جميع الرسائل", 
" Oldest - All messages":"أقدم - كل الرسائل", 
" Latest - Manual messages":"أحدث الرسائل اليدوية", 
" Oldest - Manual messages":"أقدم - الرسائل اليدوية", 
"Load More":"تحميل أكثر", 
" Confirm Delete ":"تأكيد الحذف", 
" 0 conversations will be deleted, along with all the messages & related activities. ":"سيتم حذف 0 المحادثات ، إلى جانب جميع الرسائل والأنشطة ذات الصلة.", 
" 1 conversations will be deleted, along with all the messages & related activities. ":"سيتم حذف محادثات واحدة ، إلى جانب جميع الرسائل والأنشطة ذات الصلة.", 
" 2 conversations will be deleted, along with all the messages & related activities. ":"سيتم حذف 2 محادثات ، إلى جانب جميع الرسائل والأنشطة ذات الصلة.", 
" 3 conversations will be deleted, along with all the messages & related activities. ":"سيتم حذف 3 محادثات ، إلى جانب جميع الرسائل والأنشطة ذات الصلة.", 
" 4 conversations will be deleted, along with all the messages & related activities. ":"سيتم حذف 4 محادثات ، إلى جانب جميع الرسائل والأنشطة ذات الصلة.", 
" 5 conversations will be deleted, along with all the messages & related activities. ":"سيتم حذف 5 محادثات ، إلى جانب جميع الرسائل والأنشطة ذات الصلة.", 
" 6 conversations will be deleted, along with all the messages & related activities. ":"سيتم حذف 6 محادثات ، إلى جانب جميع الرسائل والأنشطة ذات الصلة.", 
" 7 conversations will be deleted, along with all the messages & related activities. ":"سيتم حذف 7 محادثات ، إلى جانب جميع الرسائل والأنشطة ذات الصلة.", 
" 8 conversations will be deleted, along with all the messages & related activities. ":"سيتم حذف 8 محادثات ، إلى جانب جميع الرسائل والأنشطة ذات الصلة.", 
" 9 conversations will be deleted, along with all the messages & related activities. ":"سيتم حذف 9 محادثات ، إلى جانب جميع الرسائل والأنشطة ذات الصلة.", 
" Delete 0 conversations? ":"حذف 0 المحادثات؟", 
" Delete 1 conversations? ":"حذف 1 محادثات؟", 
" Delete 2 conversations? ":"حذف 2 محادثات؟", 
" Delete 3 conversations? ":"حذف 3 محادثات؟", 
" Delete 4 conversations? ":"حذف 4 محادثات؟", 
" Delete 5 conversations? ":"حذف 5 محادثات؟", 
" Delete 6 conversations? ":"حذف 6 محادثات؟", 
" Yes ":"نعم", 
" All ":"الجميع", 
" SMS ":"رسالة قصيرة", 
" Call ":"يتصل", 
" Activity ":"نشاط", 
" Appointments ":"المواعيد", 
" Invoice ":"فاتورة", 
"Fetch older messages":"إحضار الرسائل القديمة", 
"ظپظٹظ‡ ظƒظˆط¯ ط¬ط§ظ„ظƒ ط§ط³طھط£ط°ظ†ظƒ طھط±ط³ظ„ظ‡":"ظپظٹظ ‡ ظ ƒ ظˆط¯ طتباط", 
"Message Details":"تفاصيل الرسالة", 
" Download file ":"تنزيل الملف", 
"New appointment created":"تم إنشاء موعد جديد", 
"View appointment":"عرض الموعد", 
"Appointment details updated":"تفاصيل الموعد المحدثة", 
"Appointment Cancelled":"تم إلغاء الموعد", 
"WhatsApp":"Whatsapp", 
"Drag a file to this area to upload":"اسحب ملفًا إلى هذه المنطقة لتحميل", 
"Recently used":"استخدمت مؤخرا", 
"Skin tone":"لون البشرة", 
"Request Contact Details":"طلب تفاصيل الاتصال", 
"End Live Chat":"إنهاء الدردشة الحية", 
"Clear":"واضح", 
"Send":"يرسل", 
" Schedule your SMS":"جدولة الرسائل القصيرة الخاصة بك", 
"Date":"تاريخ", 
"Time":"وقت", 
"Timezone (Contact)":"المنطقة الزمنية (الاتصال)", 
"GMT+03:00 Asia/Riyadh (+03) Contact":"GMT+03: 00 ASIA/RIYADH (+03) الاتصال", 
"Cancel":"يلغي", 
"Send schedule":"إرسال الجدول الزمني", 
"Schedule your sms":"جدولة الرسائل القصيرة الخاصة بك", 
"Aug 2024":"أغسطس 2024", 
"Mon":"الاثنين", 
"Tue":"الثلاثاء", 
"Wed":"الأربعاء", 
"Thu":"الخميس", 
"Fri":"الجمعة", 
"Sat":"السبت", 
"Sun":"الأحد", 
" Send schedule ":"إرسال الجدول الزمني", 
"Contact":"اتصال", 
"Phone":"هاتف", 
"Owner (Assigned to)":"المالك (تم تعيينه إلى)", 
"Tags":"العلامات", 
"Active Automations":"أتمتة نشطة", 
"OFF":"إيقاف", 
"DND All":"DND الكل", 
"false":"خطأ", 
"DND Calls & Voicemails":"مكالمات DND والبريدات الصوتية", 
"DND Text Message":"رسالة نصية DND", 
"DND Emails":"رسائل البريد الإلكتروني DND", 
"DND GMB":"DND GMB", 
"DND Incoming":"DND الواردة", 
"No contact selected":"لم يتم تحديد جهة اتصال", 
" Add opportunity --  ":"إضافة الفرصة -", 
" Delete ":"مسح", 
"Add":"إضافة", 
"Select Template":"حدد قالب", 
" You don't have any templates yet. ":"ليس لديك أي قوالب حتى الآن.", 
"Click here to add one.":"انقر هنا لإضافة واحدة.", 
" Add to Automation ":"إضافة إلى الأتمتة", 
"Automation Type":"نوع الأتمتة", 
"Loading...":"تحميل...", 
"Campaign":"حملة", 
" is required. ":"مطلوب.", 
"Workflow":"سير العمل", 
"Event Start Date.":"تاريخ بدء الحدث.", 
"Cancel ":"إلغاء", 
" Add ":"إضافة", 
"Request payment":"طلب الدفع", 
" The details that you add below will be added to an invoice link that you can send to Abdelrahman Nasr. Invoices are created within our system and you can track the status of payments ":"ستتم إضافة التفاصيل التي تضيفها أدناه إلى رابط فاتورة يمكنك إرسالها إلى عبد الرحمن NASR.يتم إنشاء الفواتير داخل نظامنا ويمكنك تتبع حالة المدفوعات", 
"here":"هنا", 
" Contact must be attributed an email/phone to request payment. Please assign an email/phone and try again ":"يجب أن تعزى جهة الاتصال بريدًا إلكترونيًا/هاتفًا لطلب الدفع.الرجاء تعيين بريد إلكتروني/هاتف وحاول مرة أخرى", 
"How did the call go?":"كيف ذهبت المكالمة؟", 
"No Answer":"لا إجابة", 
"Busy":"مشغول", 
"Completed":"مكتمل", 
" Loading fresh data... ":"تحميل بيانات جديدة ...", 
"Initializing...":"تهيئة ...", 
"Filters":"المرشحات", 
"Calendar Settings ":"إعدادات التقويم", 
"Manage your calendars and groups":"إدارة التقويمات والمجموعات الخاصة بك", 
" Create Group":"إنشاء مجموعة", 
" Create Calendar":"إنشاء التقويم", 
"Calendars":"التقويمات", 
"Groups":"مجموعات", 
"Service Menu":"قائمة الخدمة", 
"Rooms":"غرف", 
"Equipments":"المعدات", 
"Group Name":"اسم المجموعة", 
"Date Updated":"تاريخ تحديث", 
"Status":"حالة", 
"Action Dropdown":"القائمة المنسدلة", 
"Active":"نشيط", 
"Previous":"سابق", 
"Next":"التالي", 
" Let's start ":"لنبدأ", 
"Previous":"سابق", 
"Next":"التالي", 
"Good Work!":"عمل جيد!", 
"You have no pending tasks":"ليس لديك مهام معلقة", 
"Go Back":"الرجوع", 
" MY BUSINESS ":"عملي", 
" Business Profile ":"ملف تعريف الأعمال", 
" My Profile ":"ملفي الشخصي", 
" Company Billing ":"فواتير الشركة", 
" My Staff ":"فريقي", 
" Opportunities & Pipelines ":"الفرص وخطوط الأنابيب", 
" BUSINESS SERVICES ":"خدمات الأعمال", 
" Conversation AI ":"محادثة الذكاء الاصطناعي", 
" Email Services ":"خدمات البريد الإلكتروني", 
" Phone Numbers ":"أرقام الهواتف", 
" Reputation Management ":"إدارة السمعة", 
" OTHER SETTINGS ":"إعدادات أخرى", 
" Custom Fields ":"الحقول المخصصة", 
" Custom Values ":"القيم المخصصة", 
" Manage Scoring ":"إدارة التسجيل", 
" Domains ":"المجالات", 
" URL Redirects ":"يعيد توجيه عنوان URL", 
" Integrations ":"التكامل", 
" Conversation Providers ":"مقدمي المحادثة", 
" Tags ":"العلامات", 
" Labs ":"المختبرات", 
" New ":"جديد", 
" Audit Logs ":"سجلات التدقيق", 
" Companies ":"شركات", 
"Phone System":"نظام الهاتف", 
"Manage Numbers":"إدارة الأرقام", 
"Usage Summary ":"ملخص الاستخدام", 
" Regulatory Bundle/Address ":"الحزمة التنظيمية/العنوان", 
" Trust Center ":"مركز الثقة", 
" Messaging Analytics ":"تحليلات المراسلة", 
" Advanced Settings ":"الإعدادات المتقدمة", 
" Trust Center provides products that can improve customer engagement by increasing throughput and brand recognition. ":"يوفر مركز Trust منتجات يمكن أن تحسن مشاركة العملاء عن طريق زيادة الإنتاجية والتعرف على العلامة التجارية.", 
"A2P Wizard":"معالج A2P", 
"Brands (SMS)":"العلامات التجارية (SMS)", 
"Campaigns (SMS)":"الحملات (SMS)", 
"Shaken/STIR (Voice)":"اهتز/ضجة (صوت)", 
"CNAM(Voice)":"Cnam (صوت)", 
"Voice Integrity (Voice)":"سلامة الصوت (الصوت)", 
"Voice Integrity is coming soon":"سلامة الصوت ستأتي قريبًا", 
"For more information about Voice Integrity, you can reach out to support.":"لمزيد من المعلومات حول النزاهة الصوتية ، يمكنك الوصول إلى الدعم.", 
"Click here to switch":"انقر هنا للتبديل", 
" Agency Dashboard ":"لوحة معلومات الوكالة", 
" Prospecting ":"التنقيب", 
" Sub-Accounts ":"الحسابات الفرعية", 
" Account Snapshots ":"لقطات الحساب", 
" Reselling ":"إعادة البيع", 
" Marketplace ":"السوق", 
" Affiliate Portal ":"بوابة تابعة", 
" Template Library ":"مكتبة قالب", 
" Partners ":"الشركاء", 
" University ":"جامعة", 
" SaaS Education ":"تعليم SaaS", 
" GHL Swag ":"غنيمة GHL", 
" Ideas ":"الأفكار", 
" Ai content creator ":"منشئ محتوى الذكاء الاصطناعي", 
" QR code generator ":"مولد رمز الاستجابة السريعة", 
" video meeting ":"اجتماع الفيديو", 
" You need to add calendar to start scheduling appointments. ":"تحتاج إلى إضافة تقويم لبدء جدولة المواعيد.", 
"Switch to an account":"التبديل إلى حساب", 
"CNAM (Voice)":"Cnam (صوت)", 
"Show Business Name as CallerID":"إظهار اسم العمل على أنه متصل", 
"Increase Call Pickup Rate":"زيادة معدل التقاط المكالمات", 
"A valid business registration ID is needed to register for CNAM.":"هناك حاجة إلى معرف تسجيل أعمال صالح للتسجيل في Cnam.", 
"Start Registration ":"ابدأ التسجيل", 
"Let's get you on the path to success":"دعنا نأخذك على طريق النجاح", 
" Download our app and engage with your leads on the go! ":"قم بتنزيل تطبيقنا والتفاعل مع خيوطك أثناء التنقل!", 
"Send Link":"إرسال الرابط", 
" Great! Leads and reviews from Google My Business will now show up in the system. Youâ€™ll be able to engage with them on the conversations page. ":"عظيم!سيظهر الآن قيادة ومراجعات من Google My Business في النظام.يمكنك أن تتمكن من التعامل معهم في صفحة المحادثات.", 
"Reconnect":"إعادة الاتصال", 
" Connect directly with prospects and customers via Messenger in Conversation and sync your Facebook leads with our CRM. ":"تواصل مباشرة مع الآفاق والعملاء عبر Messenger في المحادثة وقم بمزامنة خيوط Facebook الخاصة بك مع CRM لدينا.", 
"Connect":"يتصل", 
" Generate leads from your website by connecting webchat widget.":"قم بإنشاء العملاء المتوقعين من موقع الويب الخاص بك عن طريق توصيل عنصر واجهة المستخدم WebChat.", 
" (The chat widget status check may not be accurate, if the widget code is not directly embedded in the website) ":"(قد لا يكون التحقق من حالة عنصر واجهة المستخدم دقيقة ، إذا لم يكن رمز القطعة مضمنًا مباشرة في الموقع)", 
" Connect your Stripe account to start accepting payments.":"قم بتوصيل حساب الشريط الخاص بك لبدء قبول المدفوعات.", 
"(Existing stripe API integration will continue to work, but it is advised to use Stripe Connect for more security)":"(سيستمر تكامل واجهة برمجة تطبيقات Stripe الحالية في العمل ، لكن يُنصح باستخدام Stripe Connect لمزيد من الأمان)", 
" Move your WordPress site to our blazing fast and affordable hosting ":"انقل موقع WordPress الخاص بك إلى استضافتنا السريعة والمعقدة المعقولة", 
" Congratulations! Your wordpress website is on our servers":"مبروك!موقع ووردبريس الخاص بك على خوادمنا", 
" Quickly add one or more team members.":"أضف بسرعة واحدة أو أكثر من أعضاء الفريق.", 
"(The new user(s) will have the same permissions like yours except the ability to add new users.)":"(سيكون للمستخدمين (المستخدمين) الجديد نفس الأذونات مثلك باستثناء القدرة على إضافة مستخدمين جدد.)", 
" Switch to Agency View ":"التبديل إلى عرض الوكالة", 
"Search":"يبحث", 
" Quick Actions ":"إجراءات سريعة", 
"Add a Contact":"أضف جهة اتصال", 
"Add a new Contact from scratch":"أضف جهة اتصال جديدة من الصفر", 
"Book an Appointment":"حجز موعد", 
"Book a new appointment in calendar":"حجز موعد جديد في التقويم", 
"Send a Review Request":"إرسال طلب مراجعة", 
"Send a review request to the customer":"أرسل طلب مراجعة إلى العميل", 
"Create an Opportunity":"خلق فرصة", 
"Create new qualified opportunity":"إنشاء فرصة جديدة مؤهلة", 
"Go Back":"الرجوع", 
" Settings ":"إعدادات", 
" MY BUSINESS ":"عملي", 
" Business Profile ":"ملف تعريف الأعمال", 
" My Profile ":"ملفي الشخصي", 
" Company Billing ":"فواتير الشركة", 
" My Staff ":"موظفيي", 
" Opportunities & Pipelines ":"الفرص وخطوط الأنابيب", 
" BUSINESS SERVICES ":"خدمات الأعمال", 
" Automation ":"الأتمتة", 
" Calendars ":"التقويمات", 
" Conversation AI ":"محادثة الذكاء الاصطناعي", 
" Email Services ":"خدمات البريد الإلكتروني", 
" Phone Numbers ":"أرقام الهواتف", 
" Reputation Management ":"إدارة السمعة", 
" OTHER SETTINGS ":"إعدادات أخرى", 
" Custom Fields ":"الحقول المخصصة", 
" Custom Values ":"القيم المخصصة", 
" Manage Scoring ":"إدارة التسجيل", 
" Domains ":"المجالات", 
" URL Redirects ":"يعيد توجيه عنوان URL", 
" Integrations ":"التكامل", 
" Conversation Providers ":"مقدمي المحادثة", 
" Tags ":"العلامات", 
" Labs ":"المختبرات", 
" New ":"جديد", 
" Audit Logs ":"سجلات التدقيق", 
" Companies ":"شركات", 
"Schedule appointment":"جدول موعد", 
" Close ":"يغلق", 
" Save ":"يحفظ", 
"What's New":"ما الجديد", 
"Calendar Updates":"تحديثات التقويم", 
"View Changelog":"عرض changelog", 
"Notifications":"إشعارات", 
"Support":"يدعم", 
"Login As ":"تسجيل الدخول", 
"Signout":"توقيع", 
" Preferences ":"التفضيلات", 
" Availability ":"توافر", 
" Connections ":"الاتصالات", 
"Connections":"الاتصالات", 
"My Staff":"موظفيي", 
"Video Conferencing":"مؤتمرات الفيديو", 
"Google Organic Booking":"الحجز العضوي google", 
"Local Services Ads":"إعلانات الخدمات المحلية", 
"Connected Calendars":"التقويمات المتصلة", 
"No connections found ":"لم يتم العثور على اتصالات", 
"Connect your third-party calendar(s) to sync bookings and check availability":"قم بتوصيل التقويم (S) لجهة خارجية بمزامنة الحجوزات وتحقق من التوافر", 
"Add New":"أضف جديد", 
"How did the call go?":"كيف ذهبت المكالمة؟", 
"No Answer":"لا إجابة", 
"Busy":"مشغول", 
"Voicemail":"البريد الصوتي", 
"Completed":"مكتمل", 
" Loading fresh data... ":"تحميل بيانات جديدة ...", 
"Initializing...":"تهيئة ...", 
"Account Snapshots ":"لقطات الحساب", 
"Create and manage your snapshots":"قم بإنشاء لقطاتك وإدارتها", 
"My Snapshots":"لقطاتي", 
"Imported Snapshots":"لقطات مستوردة", 
"Shared Snapshots":"لقطات مشتركة", 
"Snapshot Templates":"قوالب لقطة", 
"Imported Snapshots ":"لقطات مستوردة", 
"Snapshots imported by you shows up here":"لقطات مستوردة من قبولك تظهر هنا", 
"Snapshot Name":"اسم اللقطة", 
"Imported Date":"التاريخ المستورد", 
"WL SaaS Snapshot":"WL SaaS لقطة", 
"20 / page":"20 / صفحة", 
"Account Snapshot":"لقطة الحساب", 
" Select the locations you want to update ":"حدد المواقع التي تريد تحديثها", 
"Step 1:":"الخطوة 1:", 
"Step 2:":"الخطوة 2:", 
"Step 3:":"الخطوة 3:", 
"Step 4:":"الخطوة 4:", 
"Step 5:":"الخطوة 5:", 
"You are not authorized to perform this action. Only agency admins can perform it.":"أنت غير مخول لأداء هذا الإجراء.يمكن لمشرفي الوكالة فقط أداءها.", 
" Found 0 Location linked ":"وجدت 0 موقع مرتبط", 
" Found 1 Location linked ":"وجدت موقع واحد مرتبط", 
" Found 2 Location linked ":"تم العثور على 2 موقع مرتبط", 
" Found 3 Location linked ":"تم العثور على 3 موقع مرتبط", 
" Found 4 Location linked ":"تم العثور على 4 موقع مرتبط", 
" Found 5 Location linked ":"وجدت 5 موقع مرتبط", 
" Found 6 Location linked ":"تم العثور على 6 موقع مرتبط", 
"Skip":"يتخطى", 
"Select All":"حدد كل شيء", 
"Linked Locations":"المواقع المرتبطة", 
" Proceed ":"يتابع", 
"Snapshot name":"اسم اللقطة", 
"Account":"حساب", 
"You need to pick an account.":"تحتاج إلى اختيار حساب.", 
"Save":"يحفظ", 
"Share Snapshot":"مشاركة لقطة", 
"Share Type":"مشاركة نوع", 
"Get one-time share link":"احصل على رابط مشاركة لمرة واحدة", 
"Email share link":"رابط مشاركة البريد الإلكتروني", 
"Get permanent link":"احصل على رابط دائم", 
"Get link":"احصل على رابط", 
" Manage Numbers ":"إدارة الأرقام", 
" Manage your Phone Numbers and their configuration here ":"إدارة أرقام هواتفك وتكوينها هنا", 
" Add Number ":"إضافة رقم", 
"Phone Numbers":"أرقام الهواتف", 
"Number Pools":"حمامات السباحة", 
"Verified Caller IDs":"تم التحقق من معرفات المتصل", 
"Numbers":"أرقام", 
"Friendly Name":"اسم ودود", 
"Forwarding Number":"رقم إعادة التوجيه", 
"Call Timeout":"مهلة الاتصال", 
"No Data":"لا توجد بيانات", 
"Add Phone Number":"أضف رقم الهاتف", 
"Used for SMS and Calls":"تستخدم للرسائل القصيرة والمكالمات", 
"Add Number Pool":"إضافة تجمع الأرقام", 
"Used for Lead Tracking":"تستخدم لتتبع الرصاص", 
"Add Verified CallerID":"إضافة callerid التحقق", 
"Used for callerID masking":"تستخدم لإخفاء Callerid", 
"Agency Dashboard ":"لوحة معلومات الوكالة", 
"Your current sales summary and activity.":"ملخص المبيعات الحالي ونشاطك.", 
"Connect Stripe to get started":"قم بتوصيل الشريط للبدء", 
"Please connect your Stripe account to view business KPIs.":"يرجى توصيل حساب الشريط الخاص بك لعرض Business KPIs.", 
" Connect Stripe ":"توصيل شريط", 
"Dashboard":"لوحة القيادة", 
"Promoter Reports":"تقارير المروج", 
"Payment Details":"تفاصيل الدفع", 
"Payment History":"سجل الدفع", 
"Invoice History":"تاريخ الفاتورة", 
"About":"عن", 
"Client List (Sub-Accounts)":"قائمة العميل (الحسابات الفرعية)", 
" Add Sub-Account ":"إضافة الحساب الفرعي", 
"Sub-Account transfers":"نقل الحساب الفرعي", 
"intellivay":"intellivay", 
"Switch to Sub-Account":"التبديل إلى الحساب الفرعي", 
" Manage Client ":"إدارة العميل", 
"Select Snapshot Template":"حدد قالب لقطة", 
"Team Management":"إدارة الفريق", 
" User Info ":"معلومات المستخدم", 
"Personal Logo":"الشعار الشخصي", 
"The proposed size is 512*512px":"الحجم المقترح هو 512*512 بكسل", 
"no bigger than 2.5mb":"لا يزيد حجمها عن 2.5 ميغابايت", 
" Change ":"يتغير", 
" Remove ":"يزيل", 
"First Name":"الاسم الأول", 
"Last Name":"اسم العائلة", 
"Extension":"امتداد", 
"Password":"كلمة المرور", 
"Calendar":"تقويم", 
"Select calendar":"حدد التقويم", 
" User Permissions ":"أذونات المستخدم", 
"User Permissions":"أذونات المستخدم", 
"Dashboard stats":"احصائيات لوحة القيادة", 
"Use setting":"استخدم الإعداد", 
"Appointments":"المواعيد", 
"Campaigns":"الحملات", 
"Read Only":"اقرأ فقط", 
"Bulk requests":"طلبات كبيرة", 
"Triggers":"المشغلات", 
"Funnels":"مسارات", 
"Opportunities":"فرص", 
"Conversations":"المحادثات", 
"Contacts":"جهات الاتصال", 
"Reviews":"المراجعات", 
"Online listings":"قوائم عبر الإنترنت", 
"Membership":"عضوية", 
"Certificates":"الشهادات", 
"Settings":"إعدادات", 
"Only assigned data":"البيانات المعينة فقط", 
"Lead value":"قيمة الرصاص", 
"Marketing":"تسويق", 
"Websites":"مواقع الويب", 
"Adwords Reporting":"AdWords التقارير", 
"Facebook Ads Reporting":"إعلانات Facebook الإبلاغ", 
"Call Reporting":"التقارير استدعاء", 
"Attribution Reporting":"التقارير الإسناد", 
"Social Planner":"مخطط اجتماعي", 
"Workflows":"مهام سير العمل", 
"Blogging":"التدوين", 
"Payments":"المدفوعات", 
"Invoicing":"الفواتير", 
"Record Payment":"تسجيل السجل", 
"Payment Refund":"استرداد الدفع", 
"Cancel Subscription":"إلغاء الاشتراك", 
"Affiliate Manager":"المدير التابع", 
" User Roles ":"أدوار المستخدم", 
"User Type":"نوع المستخدم", 
"Agency":"وكالة", 
"Select Account":"حدد حساب", 
"User Role":"دور المستخدم", 
" Admin ":"مسؤل", 
"Admin":"مسؤل", 
"Add To Account":"أضف إلى الحساب", 
"At least one location is required":"مطلوب موقع واحد على الأقل", 
" Call & Voicemail Settings ":"إعدادات الاتصال والبريد الصوتي", 
"Inbound Number":"رقم واردة", 
"Select Phone Number":"حدد رقم الهاتف", 
" Forward calls to web app ":"المكالمات المتابعة إلى تطبيق الويب", 
" Forward calls to mobile app ":"المكالمات المتابعة إلى تطبيق الهاتف المحمول", 
" This is only required if the users needs a dedicated number. Not required for voicemail or for routing the call to the assigned user. ":"هذا مطلوب فقط إذا كان المستخدمون يحتاجون إلى رقم مخصص.غير مطلوب للبريد الصوتي أو لتوجيه المكالمة إلى المستخدم المعين.", 
" This voicemail message will be played instead of the one by phone carrier. We recommend a timeout of 20 seconds or less. ":"سيتم تشغيل رسالة البريد الصوتي هذه بدلاً من الناقل عن طريق الهاتف.نوصي مهلة 20 ثانية أو أقل.", 
"Incoming Call Timeout":"مهلة الاتصال الواردة", 
" No timeout ":"لا مهلة", 
" 10 Secs ":"10 ثوان", 
" 20 Secs ":"20 ثانية", 
" We will record a voicemail if call isn't answered before this duration ":"سنقوم بتسجيل بريد صوتي إذا لم يتم الرد على المكالمة قبل هذه المدة", 
" mp3/wav file ":"ملف mp3/wav", 
"Upload":"رفع", 
"Shared Snapshots ":"لقطات مشتركة", 
"Snapshots shared by you shows up here":"لقطات مشتركة من قبلك تظهر هنا", 
"Updated Date":"تاريخ تحديث", 
"Shared Type":"النوع المشترك", 
"intellivay 2":"Intellivay 2", 
"Apr 25, 2024 6:15 AM":"25 أبريل ، 2024 6:15 صباحًا", 
"Permanent Link":"رابط دائم", 
" Company ":"شركة", 
" Team ":"فريق", 
" Billing ":"الفواتير", 
" Phone Integration ":"تكامل الهاتف", 
" LC - Premium Triggers & Actions ":"LC - المشغلات والإجراءات المتميزة", 
" Workflow AI ":"سير العمل الذكاء الاصطناعي", 
" Content AI ":"المحتوى الذكاء الاصطناعي", 
" Affiliates ":"الشركات التابعة", 
" Custom Menu Link ":"رابط القائمة المخصص", 
" Stripe ":"شريط", 
" API Keys ":"مفاتيح API", 
" Compliance ":"امتثال", 
"Compliance ":"امتثال", 
"Manage your team and preferences here.":"إدارة فريقك وتفضيلاتك هنا.", 
"Your Price $297/mo":"السعر الخاص بك 297 دولار/مو", 
"Suggested Reselling Price $445/mo":"سعر البيع المقترح 445 دولار/مو", 
"Weâ€™ve just released a new update!":"لقد أصدرنا للتو تحديثًا جديدًا!", 
"Check out the all new dashboard view. Pages and now load faster.":"تحقق من عرض لوحة القيادة الجديدة.الصفحات والآن تحميل أسرع.", 
"HIPAA Enabled for the whole Agency":"تمكين HIPAA للوكالة بأكملها", 
"BAA With the Agency":"BAA مع الوكالة", 
"All Security Rules Enabled":"تمكين جميع قواعد الأمن", 
"Full Encryption":"تشفير كامل", 
"Learn more":"يتعلم أكثر", 
" Buy Now":"اشتري الآن", 
"GDPR Compliance":"الامتثال الناتج المحلي الإجمالي", 
"We take the protection of your and your customer's personal data very seriously and treat personal data verfiy confidentially and in accordance with the statutory data protection regulations and this data protection declaration":"نأخذ حماية البيانات الشخصية الخاصة بك وعميلك على محمل الجد ونتعامل مع البيانات الشخصية بشكل سري ووفقًا لأنظمة حماية البيانات القانونية وإعلان حماية البيانات هذا", 
"Dashboard ":"لوحة القيادة", 
"Opportunity Status":"حالة الفرصة", 
"No data found":"لم يتم العثور على بيانات", 
"Opportunity Value":"قيمة الفرصة", 
"Conversion Rate":"معدل التحويل", 
"Won revenue":"فاز الإيرادات", 
"Funnel":"قمع", 
"Marketing Pipeline":"خط أنابيب التسويق", 
"New Lead":"تقدم جديد", 
"Hot Lead":"الرصاص الساخن", 
"New Booking":"حجز جديد", 
"Visit Attended":"تحضر زيارة", 
"Sale":"أُوكَازيُون", 
"Left a Review":"ترك مراجعة", 
"Won":"فاز", 
"Next Step":"الخطوة التالية", 
"Conversion":"تحويل", 
"Cumulative":"التراكمية", 
"Stage Distribution":"توزيع المرحلة", 
"Tasks":"المهام", 
"Pending":"قيد الانتظار", 
"Due Date (ASC)":"تاريخ الاستحقاق (ASC)", 
"Manual Actions":"الإجراءات اليدوية", 
"all":"الجميع", 
"All Users":"جميع المستخدمين", 
"Total Pending":"إجمالي معلق", 
"Go to Manual Actions ":"اذهب إلى الإجراءات اليدوية", 
"Lead Source Report":"تقرير المصدر الرئيسي", 
"Google Analytics Report":"تقرير تحليلات Google", 
" (Last 12 months)":"(آخر 12 شهرًا)", 
"Total Visitors":"إجمالي الزوار", 
"Total Page Views":"إجمالي مشاهدات الصفحة", 
"Direct Views":"وجهات النظر المباشرة", 
"Paid Views":"آراء مدفوعة الأجر", 
"Social Views":"وجهات النظر الاجتماعية", 
"Organic Views":"وجهات النظر العضوية", 
"Google Business Profile":"ملف تعريف الأعمال Google", 
" (Last 30 Days)":"(آخر 30 يومًا)", 
"Total views":"إجمالي وجهات النظر", 
"Search (Desktop & Mobile)":"البحث (سطح المكتب والجوال)", 
"Maps (Desktop & Mobile)":"الخرائط (سطح المكتب والجوال)", 
"Bookings":"الحجوزات", 
"Website visits":"زيارات الموقع", 
"Facebook Ads Report":"تقرير إعلانات الفيسبوك", 
"Total clicks":"إجمالي النقرات", 
"Total spent":"إجمالي الإنفاق", 
"CPC":"CPC", 
"CTR":"النقر إلى الورم النور", 
"Google Ads Report":"تقرير إعلانات جوجل", 
"Sales Efficiency":"كفاءة المبيعات", 
"Total Sale Value":"إجمالي قيمة البيع", 
"Sales Velocity":"سرعة المبيعات", 
"A2P Messaging":"المراسلة A2P", 
" Unverified":"لم يتم التحقق منه", 
"Brand":"ماركة", 
" Yet to Start":"حتى الآن للبدء", 
"Easy tracking and status management":"سهولة التتبع وإدارة الحالة", 
"One streamlined flow for all things A2P":"تدفق مبسط واحد لجميع الأشياء A2P", 
"Improved Delivery Rate":"تحسين معدل التسليم", 
", all SMS and MMS messages sent to U.S. phone numbers using 10DLC phone numbers will fail if not registered with an application-to-person (A2P) Campaign.":"، ستفشل جميع رسائل SMS و MMS المرسلة إلى أرقام هواتف الولايات المتحدة باستخدام أرقام هواتف 10DLC إذا لم تكن مسجلة في حملة تطبيق إلى شخص (A2P).", 
"Only required if you are sending SMS/MMS to US using a Local or Mobile number.":"مطلوب فقط إذا كنت ترسل SMS/MMS إلينا باستخدام رقم محلي أو هاتف محمول.", 
" One time and monthly campaign fee is charged for both approved and failed campaigns. Make sure to delete the campaigns which are not in use.":"يتم فرض رسوم الحملة ذات مرة وشهرية على الحملات المعتمدة والفشل.تأكد من حذف الحملات غير المستخدمة.", 
"Note:":"ملحوظة:", 
"Start Registering Now ":"ابدأ التسجيل الآن", 
"To know more":"لمعرفة المزيد", 
" click here ":"انقر هنا", 
"Send Verified Messages with A2P registration":"إرسال رسائل تم التحقق منها مع تسجيل A2P", 
"Regulatory Bundle / Address":"الحزمة التنظيمية / العنوان", 
"Regulatory Bundle is ":"الحزمة التنظيمية هي", 
" not required if you are purchasing phone numbers in the USA or Canada.":"غير مطلوب إذا كنت تشتري أرقام هواتف في الولايات المتحدة الأمريكية أو كندا.", 
" + Create ":"+ إنشاء", 
" What is Regulatory Bundle ? ":"ما هي الحزمة التنظيمية؟", 
"Country":"دولة", 
"ID":"بطاقة تعريف", 
"Address / Bundle Name":"اسم العنوان / الحزمة", 
"Type of number / Address":"نوع الرقم / العنوان", 
"Status":"حالة", 
"No Bundles Found.":"لم يتم العثور على حزم.", 
" Lead connector Phone Service ":"خدمة هاتف موصل الرصاص", 
" You need to complete few easy compliance steps to use phone systems ":"تحتاج إلى إكمال عدد قليل من خطوات الامتثال السهلة لاستخدام أنظمة الهاتف", 
"Choose which bundle you want add":"اختر الحزمة التي تريد إضافة", 
"Address Bundle":"حزمة العنوان", 
"This option will add new address to your account":"سيضيف هذا الخيار عنوانًا جديدًا إلى حسابك", 
"Regulatory Bundle":"حزمة تنظيمية", 
"This option will help you create new regulatory bundle":"سيساعدك هذا الخيار على إنشاء حزمة تنظيمية جديدة", 
" Back ":"خلف", 
" Next ":"التالي", 
"Summary ":"ملخص", 
"(updated every 24 hours)":"(تحديث كل 24 ساعة)", 
" This is visible only to Agency Admins)":"هذا واضح فقط لمشرفي الوكالة)", 
"This month so far":"هذا الشهر حتى الآن", 
"(1st Aug 2024 - Present)":"(1 أغسطس 2024 - الحاضر)", 
"Calls (0)":"المكالمات (0)", 
"Calls (1)":"المكالمات (1)", 
"Calls (2)":"المكالمات (2)", 
"Calls (3)":"المكالمات (3)", 
"Calls (4)":"المكالمات (4)", 
"Calls (5)":"المكالمات (5)", 
"Calls (6)":"المكالمات (6)", 
"Calls (7)":"المكالمات (7)", 
"Calls (8)":"المكالمات (8)", 
"Calls (9)":"المكالمات (9)", 
"Calls (10)":"الفئة (10)", 
"SMS (0)":"الرسائل القصيرة (0)", 
"SMS (1)":"الرسائل القصيرة (1)", 
"SMS (2)":"الرسائل القصيرة (2)", 
"SMS (3)":"الرسائل القصيرة (3)", 
"SMS (4)":"الرسائل القصيرة (4)", 
"SMS (5)":"الرسائل القصيرة (5)", 
"SMS (6)":"الرسائل القصيرة (6)", 
"SMS (7)":"الرسائل القصيرة (7)", 
"SMS (8)":"الرسائل القصيرة (8)", 
"SMS (9)":"الرسائل القصيرة (9)", 
"SMS (10)":"الرسائل القصيرة (10)", 
"SMS (11)":"الرسائل القصيرة (11)", 
"SMS (12)":"الرسائل القصيرة (12)", 
"SMS (13)":"الرسائل القصيرة (13)", 
"SMS (14)":"الرسائل القصيرة (14)", 
"Whatsapp (0)":"whatsapp (0)", 
"Whatsapp (1)":"whatsapp (1)", 
"Whatsapp (2)":"whatsapp (2)", 
"Whatsapp (3)":"whatsapp (3)", 
"Whatsapp (4)":"whatsapp (4)", 
"Whatsapp (5)":"whatsapp (5)", 
"LC - Premium Triggers & Actions (0)":"LC - مشغلات وإجراءات قسط (0)", 
"LC Email Verification (0)":"التحقق من البريد الإلكتروني LC (0)", 
"Content AI (0)":"المحتوى AI (0)", 
"Workflow AI (0)":"سير العمل AI (0)", 
"Conversation AI (0)":"محادثة AI (0)", 
"Emails (0)":"رسائل البريد الإلكتروني (0)", 
"Email Notifications (4)":"إشعارات البريد الإلكتروني (4)", 
"$0.0027":"0.0027 دولار", 
"WhatsApp Conversation (0)":"محادثة WhatsApp (0)", 
"Reviews AI (0)":"مراجعات منظمة العفو الدولية (0)", 
"Verified Caller ID (0)":"معرف المتصل الذي تم التحقق منه (0)", 
"Wallet Sales Tax (0)":"ضريبة مبيعات المحفظة (0)", 
"SMS Notifications (0)":"إخطارات الرسائل القصيرة (0)", 
"Email SMTP (0)":"البريد الإلكتروني SMTP (0)", 
"Other SMS Charges (0)":"رسوم الرسائل القصيرة الأخرى (0)", 
"Other Charges ":"اتهامات أخرى", 
"Call recordings":"تسجيلات الاتصال", 
"Caller Id":"معرف المتصل", 
"Validations":"عمليات التحقق", 
"Call Conference":"مؤتمر الاتصال", 
"Answering machine detection":"رد اكتشاف الجهاز", 
"Caller name":"اسم المتصل", 
"Carrier Lookups":"بحث الناقل", 
"SMS Carrier Fees":"رسوم حامل الرسائل القصيرة", 
"MMS":"MMS", 
"MMS Carrier Fees":"رسوم الناقل MMS", 
"A2P Registration Fees":"رسوم التسجيل A2P", 
"Last month":"الشهر الماضي", 
"(July 2024)":"(يوليو 2024)", 
"Email Notifications (0)":"إشعارات البريد الإلكتروني (0)", 
"The previous month":"الشهر السابق", 
"(June 2024)":"(يونيو 2024)", 
" Detailed Transactions ":"المعاملات التفصيلية", 
" Some records may take 24 hrs to update here.":"قد تستغرق بعض السجلات 24 ساعة لتحديثها هنا.", 
"Per Page":"لكل صفحة", 
" Id ":"بطاقة تعريف", 
" Billing Date ":"تاريخ الفواتير", 
" Activity Date ":"تاريخ النشاط", 
" Description ":"وصف", 
" Amount ":"كمية", 
" Balance ":"توازن", 
"Id":"بطاقة تعريف", 
"Billing Date":"تاريخ الفواتير", 
"Activity Date":"تاريخ النشاط", 
"Description":"وصف", 
"Amount":"كمية", 
"Balance":"توازن", 
"There are no records to show":"لا توجد سجلات لإظهارها", 
"Back to Trust Center":"العودة إلى مركز الثقة", 
" Shaken/STIR (Voice) ":"اهتز/ضجة (صوت)", 
" Cost free way to increase the answer rates ":"تكلفة طريقة مجانية لزيادة معدلات الإجابة", 
"Business Details":"تفاصيل الأعمال", 
"Business Address":"عنوان العمل", 
"Contact Info":"معلومات الاتصال", 
"Shaken/STIR Details":"تفاصيل اهتزاز/ضجة", 
" These details are important for your A2P approvals! ":"هذه التفاصيل مهمة لموافقات A2P الخاصة بك!", 
" DUNS for USA and CCN for Canada are not accepted for A2P Registration. ":"لا يتم قبول Duns for USA و CCN في كندا لتسجيل A2P.", 
"Legal Business Name":"اسم العمل القانوني", 
"LeadConnector Inc":"LeadConnector INC", 
" Enter the exact business name, as registered with the Government and mentioned in your tax documents (W2, W9 or CP 575). E.g. Leadconnector LLC rather than Leadconnector. ":"أدخل اسم العمل الدقيق ، كما هو مسجل في الحكومة ورده في مستنداتك الضريبية (W2 أو W9 أو CP 575).على سبيل المثالLeadConnector LLC بدلاً من LeadConnector.", 
"Business Type":"نوع العمل", 
"Select Business Type":"حدد نوع العمل", 
"Business Registration ID Type":"نوع معرف تسجيل الأعمال", 
"USA: Employer Identification Number (EIN)":"الولايات المتحدة الأمريكية: رقم تعريف صاحب العمل (EIN)", 
"Business Registration Number":"رقم تسجيل الأعمال", 
" The number used to identify your business. In case of US EIN, must be a 9-digit number e.g.12-3456789. ":"الرقم المستخدم لتحديد عملك.في حالة EIN ، يجب أن يكون رقم 9 أرقام ، على سبيل المثال 12-3456789.", 
"Business Industry":"صناعة الأعمال", 
"Select Business Industry":"حدد صناعة الأعمال", 
"Business Email":"البريد الإلكتروني التجاري", 
"Website URL":"عنوان URL موقع الويب", 
"Business Region of Operations":"منطقة أعمال العمليات", 
"Africa":"أفريقيا", 
"Asia / Pacific":"آسيا / المحيط الهادئ", 
"Europe":"أوروبا", 
"Latin America":"أمريكا اللاتينية", 
"USA & Canada":"الولايات المتحدة الأمريكية وكندا", 
"Continue":"يكمل", 
"Recruit":"تجنيد", 
"View Achievements":"عرض الإنجازات", 
"Your Lifetime Earnings":"أرباح حياتك", 
"Monthly Revenue":"الإيرادات الشهرية", 
"Customers":"عملاء", 
"Before you begin, please make sure to complete the following steps":"قبل أن تبدأ ، يرجى التأكد من إكمال الخطوات التالية", 
"Review the ":"مراجعة", 
"Affiliate Policy":"السياسة التابعة", 
"Watch Highlevel ":"مشاهدة عالية المستوى", 
"Affiliate Compliance Video":"فيديو الامتثال التابع", 
"Download the ":"تنزيل", 
"Affiliate Marketing Toolkit":"مجموعة أدوات التسويق التابعة", 
"Compliance Flowchart":"مخطط انسيابي الامتثال", 
"I have read and accepted the":"لقد قرأت وقبلت", 
"I agree and accept":"أوافق وأقبل", 
"What's New":"ما الجديد", 
"Automation Updates":"تحديثات الأتمتة", 
"Personal Data":"البيانات الشخصية", 
"Profile Image":"صورة الملف الشخصي", 
"The proposed size is 512*512 px no bigger than 2.5 MB":"الحجم المقترح هو 512*512 بكسل لا يزيد عن 2.5 ميغابايت", 
"Platform Language":"لغة المنصة", 
"English (United States)":"اللغة الإنجليزية (الولايات المتحدة)", 
"Update Profile":"تحديث الملف الشخصي", 
"Change Password":"تغيير كلمة المرور", 
"Current Password":"كلمة المرور الحالية", 
"Confirm Password":"تأكيد كلمة المرور", 
"Update Password":"تحديث كلمة المرور", 
"Marketplace Apps ":"تطبيقات السوق", 
"Get more out of your CRM. Explore apps & integrate them with your account seamlessly.":"احصل على المزيد من CRM الخاص بك.استكشف التطبيقات ودمجها مع حسابك بسلاسة.", 
"All Apps":"جميع التطبيقات", 
"Installed Apps":"التطبيقات المثبتة", 
"Manage App Permissions ":"إدارة أذونات التطبيق", 
"Collections":"مجموعات", 
"Top Installed Apps":"أعلى التطبيقات المثبتة", 
"Newly Added Apps":"التطبيقات المضافة حديثا", 
"Top Free Apps":"أفضل التطبيقات المجانية", 
"Top Paid Apps":"أفضل التطبيقات المدفوعة", 
"Custom Experience Hub":"محور الخبرة المخصصة", 
"Conversation Hub":"مركز المحادثة", 
"Categories":"فئات", 
"Pricing":"التسعير", 
"Distribution Type":"نوع التوزيع", 
"A collection of the top apps based on the number of installations.":"مجموعة من أفضل التطبيقات بناءً على عدد التثبيتات.", 
"Search Apps":"تطبيقات البحث", 
"Plai":"بلاي", 
"Run ads with AI. Whitetabel ad tool with 14+ ad platforms.":"تشغيل الإعلانات مع الذكاء الاصطناعي.أداة إعلانية Whitetabel مع 14+ منصات إعلانية.", 
"Free":"حر", 
"White-Label Verified":"تم التحقق من العلامات البيضاء", 
"Pabbly Connect":"باب", 
"By Magnet Brains Software Technology Pvt. Ltd.":"بواسطة Magnet Brains Technology Pvt.المحدود.", 
"Easily Connect Multiple Applications & Automate your Tasks!":"قم بتوصيل تطبيقات متعددة بسهولة وأتمتة مهامك!", 
"Map Leads Agency App":"خريطة يتصدر تطبيق الوكالة", 
"By Map Leads Agency Mode":"بواسطة MAP يوفر الوكالة وضع الوكالة", 
"AI Powered lead generation":"منظمة العفو الدولية التي تعمل بتوليد الرصاص", 
"Synthflow.ai - AI Phone Assistant ":"synthflow.ai - مساعد هاتف الذكاء الاصطناعي", 
"By Synthflow.ai":"بواسطة synthflow.ai", 
"Zapier by G-HL Growth Tools":"Zapier بواسطة أدوات نمو G-HL", 
"By G-HL Growth Tools":"بواسطة أدوات نمو G-HL", 
"Automations made easy!":"جعلت الأتمتة سهلة!", 
"WhatsApp Automation by WaAutoReply":"أتمتة WhatsApp بواسطة waautoreply", 
"By 21ST BUSINESS SDN BHD":"بحلول الحادي والعشرين من العمل SDN BHD", 
"Unlimited WhatsApp Automation Messaging at No Additional Cost":"رسائل أتمتة WhatsApp غير محدودة دون أي تكلفة إضافية", 
"Make by G-HL Growth Tools":"جعل بواسطة أدوات نمو G-HL", 
"WAVV":"الموجة", 
"By WAVV Communications":"بواسطة WAVV Communications", 
"Embeddable Communication Tools":"أدوات اتصال قابلة للتضمين", 
"Agency Hide Anything":"وكالة إخفاء أي شيء", 
"By Level Up Marketplace":"حسب مستوى السوق", 
"Enhanced your Dashboard Experience with agency hide anything":"عززت تجربة لوحة القيادة مع وكالة إخفاء أي شيء", 
"Consolidata":"موثوقية", 
"By Consolidata":"بواسطة Consolidata", 
"Build marketing dashboards for your agency clients in minutes!":"بناء لوحات معلومات التسويق لعملاء وكالتك في دقائق!", 
"Voizer.ai | AI Cold Caller":"Voizer.ai |منظمة العفو الدولية المتصل البارد", 
"By Agencys.ai":"بواسطة angencys.ai", 
"AI-Powered Cold Calling & Appointment Booking":"الدعوة الباردة التي تعمل بمنظمة العفو الدولية وحجز المواعيد", 
"Agency Actions":"إجراءات الوكالة", 
"Get things done. Get agency workflows.":"إنجاز الأمور.الحصول على سير عمل الوكالة.", 
"myCRMSIM SMS/MMS":"mycrmsim sms/mms", 
"By JAG Digital":"بواسطة JAG Digital", 
"Unlimited SMS using myCRMSIM through your mobile device":"الرسائل القصيرة غير المحدودة باستخدام mycrmsim من خلال جهازك المحمول", 
"Agency Knowledge Base":"قاعدة المعرفة الوكالة", 
"Leverage Collective Knowledge, Accelerate Agency Success.":"الاستفادة من المعرفة الجماعية ، تسريع نجاح الوكالة.", 
"Insighto.ai - AI Chatbot & Voice Agents":"insighto.ai - AI chatbot ووكلاء الصوت", 
"By Insighto.ai":"بواسطة Insighto.ai", 
"Automate Conversations with AI Chatbot & Voice Agents":"أتمتة المحادثات مع AI chatbot ووكلاء الصوت", 
"WhatsApp Connector":"موصل WhatsApp", 
"By Whizz Solutions":"بواسطة حلول Whiz", 
"Replace SMS with WhatsApp, send unlimited WhatsApp Messages":"استبدل الرسائل القصيرة بـ WhatsApp ، أرسل رسائل WhatsApp غير محدودة", 
"AdLaunch":"adlaunch", 
"By AdLaunch":"بواسطة Adlaunch", 
"Grow your Saas Agency, plug-in paid ads service!":"قم بتنمية وكالة SaaS الخاصة بك ، خدمة الإعلانات المكانية المدفوعة!", 
"Snapshot Onboarding":"لقطة على متن الطائرة", 
" Accelerate New User Journeys with Pre-Built Success.":"تسريع رحلات المستخدم الجديدة مع النجاح الذي تم بناؤه مسبقًا.", 
"MontyPay Payment Gateway":"بوابة الدفع Montypay", 
"By MontyPay":"بواسطة Montypay", 
"BEYOND PAYMENTS":"ما وراء المدفوعات", 
"Agency Tool Tip":"نصيحة أداة الوكالة", 
"Empower Clients with Clear Tooltips.":"تمكين العملاء مع تلميحات الأدوات الواضحة.", 
"Boomerang SaaS":"Boomerang SaaS", 
"By Boomerangme":"بواسطة Boomerangme", 
"WL Loyalty Platform for SMBs":"منصة ولاء WL لـ SMBs", 
"Calendar Updates":"تحديثات التقويم", 
" Calendar Settings ":"إعدادات التقويم", 
"Today":"اليوم", 
"Day":"يوم", 
"Week":"أسبوع", 
"Month":"شهر", 
"New":"جديد", 
"10 Sat":"10 جلس", 
"11 Sun":"11 الشمس", 
"12 Mon":"12 شهرًا", 
"13 Tue":"13 الثلاثاء", 
"14 Wed":"14 الأربعاء", 
"15 Thu":"15 الخميس", 
"16 Fri":"16 الجمعة", 
"All Day":"طوال اليوم", 
"12am":"12 صباحا", 
"1am":"1 صباحا", 
"2am":"2 صباحًا", 
"3am":"3 صباحًا", 
"4am":"4 صباحًا", 
"5am":"5 صباحا", 
"6am":"6 صباحًا", 
"7am":"7 صباحًا", 
"8am":"8 صباحا", 
"9am":"9 صباحا", 
"10am":"10 صباحًا", 
"11am":"11 صباحا", 
"12pm":"12 مساءً", 
"1pm":"1 مساءً", 
"2pm":"2 مساءً", 
"3pm":"3 مساءً", 
"4pm":"4 مساءً", 
"5pm":"5 مساءً", 
"6pm":"6 مساءً", 
"7pm":"7 مساءً", 
"8pm":"8 مساءً", 
"9pm":"9 مساءً", 
"10pm":"10 مساءً", 
"11pm":"11 مساءً", 
"Aug":"أغسطس", 
"2024":"2024", 
"Sa":"سا", 
"Su":"سو", 
"Mo":"شهر", 
"Tu":"تو", 
"We":"نحن", 
"Th":"ذ", 
"Fr":"الاب", 
"Users":"المستخدمون", 
"Calendars":"التقويمات", 
"Groups":"مجموعات", 
"Search for Group":"ابحث عن المجموعة", 
"Conversation AI":"محادثة الذكاء الاصطناعي", 
"What is Conversation AI? ":"ما هي المحادثة الذكاء الاصطناعي؟", 
"know more ":"تعرف أكثر", 
" Sub-Account Settings ":"إعدادات الحسابات الفرعية", 
"You can enable/disable Conversation AI for each sub-account ":"يمكنك تمكين/تعطيل AI للمحادثة لكل حساب فرعي", 
"3 Sub-Accounts ":"3 حسابات فرعية", 
"Search by name":"البحث بالاسم", 
"Name":"اسم", 
"Enable/Disable Feature":"ميزة تمكين/تعطيل", 
"Enable/Disable Rebilling":"تمكين/تعطيل الترددية", 
"intellivay ":"intellivay", 
" Welcome to Conversation AI ":"مرحبا بكم في محادثة الذكاء الاصطناعي", 
" We're delighted to have you join us ":"يسعدنا أن تنضم إلينا", 
"Activate conversation AI for your agency today!":"قم بتفعيل المحادثة AI لوكالتك اليوم!", 
"Enable Conversation AI":"تمكين المحادثة الذكاء الاصطناعي", 
" Please take a moment to retry your failed invoices. ":"يرجى أخذ لحظة لإعادة محيطة فواتيرك الفاشلة.", 
" Resolve Now ":"عزم الآن", 
" Dismiss ":"رفض", 
" Only Agency Admins can see this warning. For more info ":"يمكن لمشرفي الوكالة فقط رؤية هذا التحذير.لمزيد من المعلومات", 
"contact support":"الاتصال الدعم", 
"Upgrade ":"يرقي", 
"Get access to Add your own Templates to Template Library with $497 plan and higher":"احصل على إمكانية الوصول لإضافة القوالب الخاصة بك إلى مكتبة القالب بخطة 497 دولار وأعلى", 
"Not Now":"ليس الآن", 
"Upgrade Now":"الترقية الآن", 
"Labs ":"المختبرات", 
"Test out the new features before everyone else":"اختبر الميزات الجديدة قبل أي شخص آخر", 
"Welcome to our Beta Program":"مرحبًا بك في برنامج الإصدار التجريبي الخاص بنا", 
"Experiment with our latest and greatest features before they're available to everyone. These features are in early access and may change as we develop them. Your feedback will help shape what they become.":"جرب أحدث وأكبر ميزاتنا قبل توفرها للجميع.هذه الميزات في وقت مبكر وقد تتغير مع تطورها.سوف تساعد ملاحظاتك في تشكيل ما يصبحون.", 
"Granular Permissions Structure and New Functionalities":"هيكل الأذونات الحبيبية والوظائف الجديدة", 
"Whatâ€™s New:":"ما الجديد:", 
"Introduction of a granular permission structure.":"إدخال بنية إذن الحبيبية.", 
"Optimised user interface and experience.":"واجهة المستخدم المحسنة والخبرة.", 
"Show More":"تظهر المزيد", 
"Live in 13 days":"العيش في 13 يومًا", 
"Submit Feedback":"إرسال الملاحظات", 
"Client Portal Branded Mobile App":"تطبيق الهاتف المحمول الذي يحمل علامة على بوابة العميل", 
"Live in 110 days":"العيش في 110 يومًا", 
"Private Integrations":"تكامل خاص", 
"Enabling in 31 days":"التمكين في 31 يومًا", 
"Build powerful integrations between your HighLevel Agency Account and third-party apps using simple, easy-to-manage API Tokens. With Private Integr...":"قم ببناء تكاملات قوية بين حساب الوكالة العالية وتطبيقات الطرف الثالث باستخدام رموز API بسيطة وسهلة الإدارة.مع التكامل الخاص ...", 
"Live in 31 days":"العيش في 31 يومًا", 
"To activate conversation AI please contact us.":"لتفعيل المحادثة الذكاء الاصطناعي يرجى الاتصال بنا.", 
"Go to Settings":"انتقل إلى الإعدادات", 
"Workflow AI":"سير العمل الذكاء الاصطناعي", 
"What is Workflow AI? ":"ما هو سير العمل من الذكاء الاصطناعي؟", 
"know more":"تعرف أكثر", 
"Sub-Account Settings":"إعدادات الحسابات الفرعية", 
"3 Sub-Accounts":"3 حسابات فرعية", 
"You can enable/disable Workflow AI for each Sub-Account":"يمكنك تمكين/تعطيل الذكاء الاصطناعي لكل حساب فرعي", 
"Actions ":"الإجراءات", 
"Campaign ID":"معرف الحملة", 
"Campaign status":"حالة الحملة", 
"Connected Brand":"العلامة التجارية المتصلة", 
"Messaging Service":"خدمة المراسلة", 
"Use Case":"استخدام الحالة", 
" Preferences ":"التفضيلات", 
" Availability ":"توافر", 
" Connections ":"الاتصالات", 
"Connections":"الاتصالات", 
"My Staff":"موظفيي", 
"Video Conferencing":"مؤتمرات الفيديو", 
"Google Organic Booking":"الحجز العضوي google", 
"Local Services Ads":"إعلانات الخدمات المحلية", 
"Connected Calendars":"التقويمات المتصلة", 
"No connections found ":"لم يتم العثور على اتصالات", 
"Connect your third-party calendar(s) to sync bookings and check availability":"قم بتوصيل التقويم (S) لجهة خارجية بمزامنة الحجوزات وتحقق من التوافر", 
"Add New":"أضف جديد", 
"Company Billing":"فواتير الشركة", 
"Add payment method":"أضف طريقة الدفع", 
"Add Payment method ":"أضف طريقة الدفع", 
" Do not add your own card to sub-accounts !! ":"لا تضيف بطاقتك الخاصة إلى الحسابات الفرعية !!", 
" Please add your client's (sub-account's) card and not your own as this card will be used to bill your client on your behalf. The funds will be deposited in your Stripe account connected in ":"يرجى إضافة بطاقة العميل (الحساب الفرعي) وليس خاصتك لأن هذه البطاقة سيتم استخدامها لفواتير عميلك نيابة عنك.سيتم إيداع الأموال في حساب الشريط الخاص بك المتصل في", 
"Agency Settings":"إعدادات الوكالة", 
"Add Card":"أضف بطاقة", 
"Card Details":"تفاصيل البطاقة", 
" Add Card ":"أضف بطاقة", 
"Remove Card?":"إزالة البطاقة؟", 
"Ending in *-1":"تنتهي في *-1", 
"No":"لا", 
" Yes, Remove ":"نعم ، أزل", 
"Add money to Wallet":"أضف أموالًا إلى محفظة", 
" Please provide an amount between 1 and 10000. ":"يرجى تقديم مبلغ ما بين 1 و 10000.", 
" Current Balance: ":"التوازن الحالي:", 
"Money will be added to your wallet ":"سيتم إضافة المال إلى محفظتك", 
"Brand SID":"العلامة التجارية سيد", 
"Brand status":"حالة العلامة التجارية", 
"Brand type":"نوع العلامة التجارية", 
"Identity Status":"حالة الهوية", 
"Brand Submission Attempts":"محاولات تقديم العلامة التجارية", 
"Date Created":"تم إنشاؤها التاريخ", 
"Create new message ":"إنشاء رسالة جديدة", 
"Select Contact":"حدد جهة الاتصال", 
"Select name, email or phone":"حدد الاسم أو البريد الإلكتروني أو الهاتف", 
" Opportunity ":"فرصة", 
" Add An Opportunity ":"أضف فرصة", 
"No opportunities found":"لا توجد فرص", 
" Book Appointment ":"موعد الكتاب", 
" Past Appointments ":"المواعيد السابقة", 
"Cancelled ":"ألغى", 
"AM":"أكون", 
"(No location added)":"(لا يوجد موقع)", 
"Confirmed ":"مؤكد", 
"Reselling":"إعادة البيع", 
"Core Services":"الخدمات الأساسية", 
"Marketplace Apps":"تطبيقات السوق", 
" Markup and Resell: Marketplace Apps from Third-Party Developers. Sub-Accounts will pay the marked-up price set here upon installation. ":"Markup و Resell: تطبيقات Marketplace من مطوري الطرف الثالث.ستدفع الحسابات الفرعية السعر المحدد هنا عند التثبيت.", 
"Learn More.":"يتعلم أكثر.", 
" Re-Sell test-dual ":"إعادة بيع الاختبار المزدوج", 
"App Plans":"خطط التطبيق", 
"Build your Up-sell offer":"قم ببناء عرض الخاص بك", 
"HighLevel Price":"سعر مرتفع", 
"Your Price":"سعرك", 
"Profit":"ربح", 
" Re-Sell Import Custom Fields  ":"إعادة بيع الحقول المخصصة للاستيراد", 
"Unlimited":"غير محدود", 
" Re-Sell Manage Opportunities ":"إعادة البيع إدارة الفرص", 
" This app offers a 7 day free trial. ":"يوفر هذا التطبيق تجربة مجانية لمدة 7 أيام.", 
" Re-Sell Import Custom Values ":"إعادة بيع القيم المخصصة استيراد", 
" Notes ":"ملحوظات", 
" Add Note ":"أضف ملاحظة", 
" Created by":"تم إنشاؤها بواسطة", 
"System":"نظام", 
"Back":"خلف", 
"Easily connect your third-party calendar(s) to check availability, update appointments as they're scheduled and avoid double bookings.":"قم بسهولة بتوصيل التقويم (التقويمات) من الطرف الثالث للتحقق من توافر المواعيد وتحديث المواعيد أثناء تحديد موعدها وتجنب الحجوزات المزدوجة.", 
"Google Calendar ":"تقويم جوجل", 
"Connect your Google Calendar":"قم بتوصيل تقويم Google الخاص بك", 
"Outlook Calendar ":"التقويم Outlook", 
"Connect your Office 365, Outlook.com, live.com, or hotmail calendar":"قم بتوصيل Office 365 أو Outlook.com أو Live.com أو Hotmail Calendar", 
"iCloud Calendar ":"تقويم iCloud", 
"Connect your iCloud Calendar":"قم بتوصيل تقويم iCloud الخاص بك", 
"Calendly ":"تقويم", 
" Beta ":"بيتا", 
"Connect your Calendly account to sync all calendly events into the system":"قم بتوصيل حسابك التقويمي لمزامنة جميع أحداث التقويم في النظام", 
"Automatically generate unique meeting links and share them whenever an appointment is scheduled.":"قم بإنشاء روابط اجتماعات فريدة تلقائيًا ومشاركتها كلما تم جدولة موعد.", 
"Zoom ":"تكبير", 
"Connect Zoom to generate a unique meeting link each time":"قم بتوصيل التكبير لإنشاء رابط اجتماع فريد في كل مرة", 
"Clone":"استنساخ", 
"Duplicate to another account":"تكرار إلى حساب آخر", 
"Set as default dashboard":"تعيين كوحة القيادة الافتراضية", 
"Manage Dashboard Timezone":"إدارة المنطقة الزمنية لوحة القيادة", 
"Manage permissions":"إدارة الأذونات", 
"Delete":"يمسح", 
"Manage equipments for your business here":"إدارة المعدات لعملك هنا", 
" Create Equipment":"إنشاء المعدات", 
"Equipment Name":"اسم المعدات", 
"Name":"اسم", 
"Total Quantity":"الكمية الكلية", 
"Services Associated to":"الخدمات المرتبطة", 
"No equipments found":"لم يتم العثور على معدات", 
"No equipments found in this location":"لا توجد معدات موجودة في هذا الموقع", 
" Add new Equipment":"أضف معدات جديدة", 
"Add/Edit Equipment ":"إضافة/تحرير المعدات", 
"Add or edit an equipment":"إضافة أو تحرير جهاز", 
"Description":"وصف", 
"Out of Service Quantity":"خارج كمية الخدمة", 
"Select calendar":"حدد التقويم", 
"You can select multiple service calendars to associate with equipments":"يمكنك تحديد تقويمات خدمة متعددة لربطها بالمعدات", 
"Please Select":"الرجاء تحديد", 
"Cancel":"يلغي", 
"Create":"يخلق", 
"Search for User":"ابحث عن المستخدم", 
"1 Apps":"1 تطبيقات", 
"2 Apps":"2 تطبيقات", 
"3 Apps":"3 تطبيقات", 
"4 Apps":"4 تطبيقات", 
"5 Apps":"5 تطبيقات", 
"No apps found":"لم يتم العثور على تطبيقات", 
"You can search for an integration or go to â€œAll Appsâ€‌ to check out list of all available Apps.":"يمكنك البحث عن تكامل أو الانتقال إلى ",
"All Apps":"للتحقق من قائمة جميع التطبيقات المتاحة.", 
" View all Apps":"عرض جميع التطبيقات", 
"Custom Menu Links":"روابط قائمة مخصصة", 
"Create & manage custom menu links for agency & sub-accounts":"قم بإنشاء وإدارة روابط القائمة المخصصة للوكالة والحسابات الفرعية", 
" Create New":"إنشاء جديد", 
"Icon":"رمز", 
"Title":"عنوان", 
"URL":"عنوان URL", 
"Open mode":"فتح الوضع", 
"Show on":"عرض على", 
"Total Accounts":"إجمالي الحسابات", 
"Ai content creator":"منشئ محتوى الذكاء الاصطناعي", 
"Agency, Account":"وكالة ، حساب", 
"QR code generator":"مولد رمز الاستجابة السريعة", 
"video meeting":"اجتماع الفيديو", 
"whatsapp intellivay":"Whatsapp intellivay", 
"Account":"حساب", 
"whatsapp Bestview":"WhatsApp BestView", 
"whatsapp Rawin":"Whatsapp Rawin", 
"whatsapp intellivay 2":"whatsapp intellivay 2", 
"Whatsapp":"Whatsapp", 
"book":"كتاب", 
"Create a custom menu link ":"قم بإنشاء رابط قائمة مخصص", 
"Link Icon":"أيقونة الارتباط", 
"Click to select icon":"انقر لتحديد الأيقونة", 
"Link Title":"عنوان الرابط", 
"Link Name":"اسم الرابط", 
"Link URL":"رابط عنوان URL", 
"Sidebar Preference":"تفضيل الشريط الجانبي", 
"Show link on Agency sidebar":"عرض رابط على الشريط الجانبي للوكالة", 
"Show link on Account sidebar":"إظهار الرابط على الشريط الجانبي الحساب", 
"Show to all accounts":"عرض لجميع الحسابات", 
"When Clicked":"عند النقر عليها", 
"Open in iFrame inside the platform":"افتح في iframe داخل المنصة", 
"Open in a New Tab":"افتح في علامة تبويب جديدة", 
"Open in Current Window":"افتح في النافذة الحالية", 
"Permissions":"أذونات", 
"Allow Microphone":"السماح للميكروفون", 
"Allow Camera":"السماح للكاميرا", 
"Save":"يحفظ", 
" Pipelines ":"خطوط الأنابيب", 
"Customise opportunity settings":"تخصيص إعدادات الفرص", 
"Allow different owners of Contacts and their Opportunities":"السماح لأصحاب الاتصالات المختلفين وفرصهم", 
" Note: If setting is ON, workflows might stop assigning owners to opportunities.":"ملاحظة: إذا كان الإعداد قيد التشغيل ، فقد تتوقف سير العمل عن تعيين أصحاب الفرص.", 
"Learn more about this setting.":"تعرف على المزيد حول هذا الإعداد.", 
"Automatically make Opportunity owner a follower of Contact ":"اجعل مالك الفرصة تلقائيًا تابعًا للاتصال", 
"When a new owner is selected for an opportunity, they will be added as a follower to the contact of that opportunity.":"عندما يتم اختيار مالك جديد للحصول على فرصة ، سيتم إضافتها كمتابع للاتصال بهذه الفرصة.", 
"Automatically make Contact owner a follower of the Opportunity ":"اجعل مالك الاتصال تلقائيًا تابعًا للفرصة", 
"When a new owner is selected for a contact, they will be added as a follower to the opportunities of that contact.":"عندما يتم اختيار مالك جديد للاتصال ، سيتم إضافتها كمتابع لفرص هذا الاتصال.", 
"Save Changes":"حفظ التغييرات", 
"Opportunities & Pipelines":"الفرص وخطوط الأنابيب", 
"Stripe Integration":"تكامل الشريط", 
" HighLevel will have access to your data, and can create payments and customers on your behalf ":"ستحصل Highlevel على إمكانية الوصول إلى بياناتك ، ويمكنها إنشاء مدفوعات وعملاء نيابة عنك", 
" Once connected the Stripe account cannot be changed later. It is recommended to use a new Stripe account dedicated to Highlevel earnings. ":"بمجرد توصيل حساب الشريط في وقت لاحق.يوصى باستخدام حساب شريط جديد مخصص لأرباح المستوى العالي.", 
" Connect to your Stripe account ":"الاتصال بحساب الشريط الخاص بك", 
"Manage rooms for your business here":"إدارة الغرف لعملك هنا", 
" Create Room":"إنشاء مساحة", 
"Room Name":"اسم الغرفة", 
"Total Capacity":"إجمالي السعة", 
"room 3":"الغرفة 3", 
"room 2":"الغرفة 2", 
"Room 1":"الغرفة 1", 
"Edit":"يحرر", 
"Disable Room":"تعطيل الغرفة", 
"Delete":"يمسح", 
"My Snapshots ":"لقطاتي", 
"Snapshots created by you shows up here":"اللقطات التي أنشأتها تظهر هنا", 
"Create New Snapshot":"إنشاء لقطة جديدة", 
"Sub Account":"الحساب الفرعي", 
"Created On":"تم إنشاؤها على", 
"Last Update On":"آخر تحديث على", 
"websites snapshot":"لقطة مواقع الويب", 
"restuarant":"مطعم", 
"Calendar Name":"اسم التقويم", 
"Filters":"المرشحات", 
"Group":"مجموعة", 
"Duration (mins)":"المدة (دقيقة)", 
"Calendar Type":"نوع التقويم", 
"Service":"خدمة", 
"Click here to switch":"انقر هنا للتبديل", 
" Company ":"شركة", 
" Team ":"فريق", 
" Billing ":"الفواتير", 
" Phone Integration ":"تكامل الهاتف", 
" LC - Premium Triggers & Actions ":"LC - المشغلات والإجراءات المتميزة", 
" Workflow AI ":"سير العمل الذكاء الاصطناعي", 
" Content AI ":"المحتوى الذكاء الاصطناعي", 
" Affiliates ":"الشركات التابعة", 
" Custom Menu Link ":"رابط القائمة المخصص", 
" Stripe ":"شريط", 
" API Keys ":"مفاتيح API", 
" Compliance ":"امتثال", 
" You need to add calendar to start scheduling appointments. ":"تحتاج إلى إضافة تقويم لبدء جدولة المواعيد.", 
"Switch to an account":"التبديل إلى حساب", 
" You have one or more failed payments. Please check your billing history. ":"لديك مدفوعات واحدة أو أكثر.يرجى التحقق من سجل الفواتير الخاص بك.", 
"Ignore":"يتجاهل", 
"More Info":"مزيد من المعلومات", 
"Affiliate Settings":"الإعدادات التابعة", 
"You can append this to the following URLs for easy tracking: ":"يمكنك إلحاق ذلك بعناوين URL التالية لسهولة التتبع:", 
"Go to the URL: ":"اذهب إلى عنوان URL:", 
" and sign up using the email address ":"والتسجيل باستخدام عنوان البريد الإلكتروني", 
" as your email address for FirstPromoter. ":"كعنوان بريدك الإلكتروني لـ FirstPromoter.", 
"Need to sign up?":"تحتاج إلى الاشتراك؟", 
"Page Settings":"إعدادات الصفحة", 
"Facebook Pixel ID":"معرف البكسل فيسبوك", 
"Automotive":"السيارات", 
"Auto Dealers/Sales":"تجار السيارات/المبيعات", 
"Automotive Repair/Mechanic":"إصلاح السيارات/ميكانيكي", 
"Financial":"مالي", 
"Bookkeeper":"محاسب", 
"Business Coaching & Consulting":"تدريب الأعمال والاستشارات", 
"Business Coaching":"تدريب الأعمال", 
"Car Detailing":"تفاصيل السيارة", 
"Career Coach":"مدرب مهني", 
"Medical":"طبي", 
"Chiropractor":"مقوم العظام", 
"Beauty & Fashion":"الجمال والأزياء", 
"Day Spa":"سبا اليوم", 
"Dental":"طب الأسنان", 
"Legal":"قانوني", 
"Family Lawyer":"محامي الأسرة", 
"Creative":"مبدع", 
"Graphic Design":"تصميم الجرافيك", 
"Health & Wellness":"الصحة والعافية", 
"Gym":"نادي رياضي", 
"Hair Salon":"صالون الشعر", 
"Holistic Wellness":"العافية الشاملة", 
"Home Services":"الخدمات المنزلية", 
"Landscaping":"المناظر الطبيعية", 
"Marketing Agency":"وكالة التسويق", 
"Medical Spa":"المنتجع الصحي الطبي", 
"Insurance":"تأمين", 
"P&C Insurance":"تأمين P&C", 
"Plumber":"سباك", 
"Real Estate":"العقارات", 
"Real Estate Agent":"وكيل العقارات", 
"Restaurant & Bar":"مطعم وبار", 
"Steakhouse":"ستيك هاوس", 
"Finance":"تمويل", 
"Tax Accounting":"المحاسبة الضريبية", 
"Travel & Hospitality":"السفر والضيافة", 
"Travel Agency":"وكالة السفر", 
"Web Designer":"مصمم الويب", 
"Wellness Coaching":"تدريب العافية", 
"Yoga":"اليوغا", 
" Message Templates (Snippets) ":"قوالب الرسائل (مقتطفات)", 
"1 templates":"1 قوالب", 
"2 templates":"2 قوالب", 
"3 templates":"3 قوالب", 
"5 templates":"5 قوالب", 
"6 templates":"6 قوالب", 
" Add Template (Snippet) ":"إضافة قالب (مقتطف)", 
"Add Text Template (Snippet)":"أضف قالب نص (مقتطف)", 
"Add Email Template (Snippet)":"أضف قالب البريد الإلكتروني (مقتطف)", 
" Name ":"اسم", 
" Body ":"جسم", 
" Attachments ":"المرفقات", 
" Type ":"يكتب", 
" What services do you offer? ":"ما هي الخدمات التي تقدمها؟", 
"text":"نص", 
" What times are your Day Spa open? ":"ما هي الأوقات التي تفتح فيها سبا يومك؟", 
" Compose SMS Text Template ":"يؤلف قالب نص الرسائل القصيرة", 
"Attach File ":"إرفاق الملف", 
"Enter message":"أدخل الرسالة", 
" Send ":"يرسل", 
" Send test ":"إرسال الاختبار", 
" Compose Email Template ":"تأليف قالب البريد الإلكتروني", 
"Send Test":"إرسال الاختبار", 
"From Address":"من العنوان", 
"To Address":"لمعالجة", 
" Starting June 17, 2024, Enhanced Account Security will be automatically enabled on your account by default. The enhanced security enhancements include: ":"ابتداءً من 17 يونيو 2024 ، سيتم تمكين أمان الحساب المحسّن تلقائيًا على حسابك افتراضيًا.تشمل التحسينات الأمنية المعززة:", 
" To opt-out of this change, please disable Enhanced Account Security in ":"لإلغاء الاشتراك في هذا التغيير ، يرجى تعطيل أمان الحساب المحسّن في", 
"Discontinuation of Auto-generation of Location API keys":"توقف عن تولي من مفاتيح مفاتيح واجهة برمجة تطبيقات الموقع", 
"Exclusion of API Keys in Location CRUD APIs":"استبعاد مفاتيح API في موقع واجهات برمجة التطبيقات", 
"Settings > Company":"الإعدادات> الشركة", 
" This API is for advanced functionality. Our support team is not able to provide direct assistance regarding the API configuration. ":"API هذا هو للوظائف المتقدمة.فريق الدعم الخاص بنا غير قادر على تقديم المساعدة المباشرة فيما يتعلق بتكوين API.", 
" We do offer a Developer Council which meets for office hours once a month (":"نحن نقدم مجلس مطور يجتمع لساعات المكاتب مرة واحدة في الشهر (", 
"Agency API Keys":"وكالة مفاتيح API", 
"This is part of the Advanced API that is available on the Pro Plan. ":"هذا جزء من واجهة برمجة التطبيقات المتقدمة المتوفرة على خطة Pro.", 
" to upgrade.":"للترقية.", 
"Click here":"انقر هنا", 
" Create API Key ":"إنشاء مفتاح API", 
" Location API Key ":"مفتاح واجهة برمجة تطبيقات الموقع", 
" Delete All Keys ":"حذف جميع المفاتيح", 
"API Key":"مفتاح API", 
"Generated By":"ولدت من قبل", 
"Created At":"تم إنشاؤها في", 
"Last Used At":"آخر استخدام في", 
"Action":"فعل", 
" Delete all Location API keys? ":"حذف جميع مفاتيح واجهة برمجة تطبيقات الموقع؟", 
" This action cannot be reversed. ":"لا يمكن عكس هذا الإجراء.", 
"Are you sure you want to delete all the locations api keys? ":"هل أنت متأكد من أنك تريد حذف جميع مفاتيح API المواقع؟", 
" Confirm deletion by typing ":"تأكيد الحذف عن طريق الكتابة", 
" below: ":"أقل:", 
"CONFIRM":"يتأكد", 
" Cancel, Keep ":"إلغاء ، واصل", 
"Yes, Delete ":"نعم ، حذف", 
"Business Profile Settings":"إعدادات ملف تعريف الأعمال", 
"Manage your business profile information & settings":"إدارة معلومات وإعدادات ملف تعريف ملفك التجاري", 
"General Information":"معلومات عامة", 
"Location ID":"معرف الموقع", 
"Business Logo":"شعار العمل", 
"The proposed size is 350px * 180px. No bigger than 2.5 MB":"الحجم المقترح هو 350 بكسل * 180 بكسل.لا يزيد حجمها عن 2.5 ميغابايت", 
"Upload":"رفع", 
"Remove":"يزيل", 
"Friendly Business Name":"اسم الأعمال الودية", 
"Legal Business Name ":"اسم العمل القانوني", 
"Legal Business Name":"اسم العمل القانوني", 
"Enter the exact legal business name, as registered with the EIN":"أدخل اسم العمل القانوني الدقيق ، كما هو مسجل لدى EIN", 
"Business Email":"البريد الإلكتروني التجاري", 
"Business Phone":"هاتف العمل", 
"Branded Domain ":"المجال ذو العلامات التجارية", 
"Branded Domain":"المجال ذو العلامات التجارية", 
"Add Domain":"إضافة المجال", 
"Business Website":"موقع الأعمال", 
"Business Niche":"مكان العمل", 
"Massage Spa":"تدليك سبا", 
"API Key":"مفتاح API", 
"Generate Key":"توليد المفتاح", 
"Update Information":"تحديث المعلومات", 
"Business Information":"معلومات الأعمال", 
"Business Type":"نوع العمل", 
"Pick Business Type":"اختيار نوع العمل", 
"Business Industry":"صناعة الأعمال", 
"Pick Business Industry":"اختيار صناعة الأعمال", 
"Business Registration ID Type":"نوع معرف تسجيل الأعمال", 
"Pick Business Registration ID Type":"اختر نوع معرف تسجيل الأعمال", 
"Business Registration Number":"رقم تسجيل الأعمال", 
"My business is Not registered":"عملي غير مسجل", 
"Business Regions of Operations":"مناطق العمليات التجارية", 
"Africa":"أفريقيا", 
"Asia":"آسيا", 
"Europe":"أوروبا", 
"Latin America":"أمريكا اللاتينية", 
"USA and Canada":"الولايات المتحدة الأمريكية وكندا", 
"Call & Voicemail Settings":"إعدادات الاتصال والبريد الصوتي", 
"This is the default voicemail message for all phone numbers in the location unless customized under ":"هذه هي رسالة البريد الصوتي الافتراضي لجميع أرقام الهواتف في الموقع ما لم يتم تخصيصها تحت", 
" settings":"إعدادات", 
"Team Management":"إدارة الفريق", 
"This voicemail message will be played instead of the one by phone carrier. We recommend a timeout of 20 seconds or less.":"سيتم تشغيل رسالة البريد الصوتي هذه بدلاً من الناقل عن طريق الهاتف.نوصي مهلة 20 ثانية أو أقل.", 
"Incoming Call Timeout ":"مهلة الاتصال الواردة", 
"No timeout":"لا مهلة", 
" mp3/wav File":"ملف mp3/wav", 
"Save Call Settings":"حفظ إعدادات المكالمات", 
"Business Physical Address":"العنوان الفعلي للأعمال", 
"Street Address":"عنوان الشارع", 
"City":"مدينة", 
"Postal/Zip Code":"الرمز البريدي/البريدي", 
"State / Prov / Region":"الدولة / الإقليم / المنطقة", 
"Country":"دولة", 
"Saudi Arabia":"المملكة العربية السعودية", 
"Time Zone":"المنطقة الزمنية", 
"Platform Language ":"لغة المنصة", 
"English (United States)":"اللغة الإنجليزية (الولايات المتحدة)", 
"Outbound communication language for custom values ":"لغة الاتصال الخارجية للقيم المخصصة", 
"Update":"تحديث", 
"Authorized Representative":"ممثل معتمد", 
"First Name":"الاسم الأول", 
"Last Name":"اسم العائلة", 
"Representative Email":"البريد الإلكتروني التمثيلي", 
"Job Position":"موقف الوظيفة", 
"Phone Number (With Country Code)":"رقم الهاتف (مع رمز البلد)", 
"General":"عام", 
"Allow Duplicate Opportunity":"السماح الفرصة مكررة", 
"Merge Facebook Contacts By Name":"دمج جهات اتصال Facebook بالاسم", 
"Disable Contact Timezone":"تعطيل المنطقة الزمنية الاتصال", 
"Bot Detection Preventing Statistics Increment and Automation Execution":"اكتشاف الروبوت يمنع زيادة الإحصاءات وتنفيذ الأتمتة", 
"Mark Emails as Invalid due to Hard Bounce":"وضع علامة على رسائل البريد الإلكتروني على أنها غير صالحة بسبب الارتداد الصعب", 
"Validate Phone numbers when first SMS is sent to a new contact":"التحقق من صحة أرقام الهواتف عند إرسال الرسائل القصيرة الأولى إلى جهة اتصال جديدة", 
"Verify Email Address when first email is sent to a new contact.":"تحقق من عنوان البريد الإلكتروني عند إرسال البريد الإلكتروني الأول إلى جهة اتصال جديدة.", 
"Make SMS compliant by adding an opt out message.":"اجعل SMS متوافقًا عن طريق إضافة رسالة إلغاء الاشتراك.", 
"How does it work?":"كيف تعمل؟", 
"Reply STOP to Unsubscribe":"الرد توقف إلى إلغاء الاشتراك", 
"Customize":"تخصيص", 
"Make SMS compliant by adding a sender information.":"اجعل SMS متوافقًا عن طريق إضافة معلومات المرسل.", 
"Make Email compliant by adding an Unsubscribe link in your email.":"اجعل البريد الإلكتروني متوافقًا عن طريق إضافة رابط إلغاء الاشتراك في بريدك الإلكتروني.", 
"Contact Deduplication Preferences":"الاتصال تفضيلات التكلفة المستهلكة", 
"Allow Duplicate Contact":"السماح بالاتصال المكررة", 
"Find existing contacts based on":"ابحث عن جهات الاتصال الحالية بناءً على", 
"Email":"بريد إلكتروني", 
"Second preference for search (Optional)":"التفضيل الثاني للبحث (اختياري)", 
"Phone":"هاتف", 
"Missed Call Text Back":"مفقود نص المكالمات مرة أخرى", 
"Enable missed call text back":"تمكين نص المكالمة الفائتة مرة أخرى", 
"Missed Text Back Call Message":"رسالة استدعاء النص الفائتة", 
"Mobile Phone Number":"رقم الهاتف المحمول", 
"Send Test":"إرسال الاختبار", 
"Save Missed Call Text Settings":"حفظ إعدادات نص المكالمات الفائتة", 
"Conversation AI Reselling":"محادثة منظمة العفو الدولية إعادة بيع", 
"Re-sell Conversation AI":"إعادة بيع المحادثة الذكاء الاصطناعي", 
"How does it work?":"كيف تعمل؟", 
"Build Your Re-sell Offer":"بناء عرض إعادة البيع الخاص بك", 
"Your Profit":"ربحك", 
" Kindly enable Conversation AI for your agency in Company Settings ":"يرجى تمكين المحادثة AI لوكالتك في إعدادات الشركة", 
" Yext Reselling":"إعادة بيع Yext", 
"Re-sell Yext Listing":"إعادة بيع قائمة yext", 
" HighLevel gives you a discount compared to the stock rate which is usually billed at $999 with yearly commitment. HighLevel's wholesale price is just $30/month with only 1 month commitment ":"يمنحك Highlevel خصمًا مقارنة بسعر الأسهم الذي يتم فواتيره عادةً بمبلغ 999 دولارًا مع التزام سنوي.سعر الجملة في Highlevel هو 30 دولارًا شهريًا فقط مع التزام شهر واحد فقط", 
"WhatsApp Reselling":"إعادة بيع Whatsapp", 
"Re-sell WhatsApp":"أعد بيع whatsapp", 
" Receiving Inbound messages and replying to them using a free text in the conversation window are free. There will be additional pass through charges for outbound template messages if sent. ":"تلقي الرسائل الواردة والرد عليها باستخدام نص مجاني في نافذة المحادثة مجانًا.سيكون هناك تمريرة إضافية من خلال رسوم لرسائل القالب الصادرة إذا تم إرسالها.", 
" Wordpress Reselling":"إعادة بيع WordPress", 
"Re-sell Wordpress":"إعادة بيع WordPress", 
"Standard Pricing":"التسعير القياسي", 
"Selected":"محدد", 
" Ad Manager Reselling ":"مدير الإعلان إعادة بيع", 
" Re-sell Ad Manager ":"إعادة بيع مدير الإعلان", 
" Select an Ad manager service ":"حدد خدمة مدير الإعلانات", 
"Default Ad Manager":"مدير الإعلان الافتراضي", 
"Connect-Your-Own Meta Business Manager":"توصيل مدير أعمال META الخاص بك", 
" I agree this is a one time action and cannot be reverted ":"أوافق على أن هذا إجراء لمرة واحدة ولا يمكن العودة إليه", 
" The selected payment scheme will be same for all your sub-accounts and it cannot be altered once service model is finalised as either of the two mentioned above. ":"سيكون نظام الدفع المحدد هو نفسه بالنسبة لجميع عمليات الحسابات الفرعية الخاصة بك ولا يمكن تغييره بمجرد الانتهاء من نموذج الخدمة مثل أي من الاثنين المذكورة أعلاه.", 
"Content AI - Text And Image":"المحتوى AI - النص والصورة", 
"What is Content AI - Text And Image? ":"ما هو المحتوى الذكاء الاصطناعي - النص والصورة؟", 
"You can enable/disable Content AI - Text And Image for each Sub-Account":"يمكنك تمكين/تعطيل المحتوى AI - نص وصورة لكل حساب فرعي", 
" Tasks ":"المهام", 
" Add Task ":"أضف المهمة", 
"No tasks found":"لم يتم العثور على مهام", 
"Analyze":"تحليل", 
"Trigger links allow you to put links inside SMS messages and emails, which allow you to track specific customer actions and trigger events based on when the link is clicked.":"تتيح لك روابط المشغل وضع روابط داخل رسائل الرسائل القصيرة ورسائل البريد الإلكتروني ، والتي تتيح لك تتبع إجراءات العملاء المحددة وتشغيل الأحداث بناءً على متى يتم النقر على الرابط.", 
"Link URL":"رابط عنوان URL", 
"Actions":"الإجراءات", 
"My Google Reviews Link":"رابط مراجعات Google الخاص بي", 
" No records found. ":"لم يتم العثور على سجلات.", 
"Add Trigger Link":"إضافة رابط الزناد", 
"Manage your calendars, groups and service menu":"إدارة التقويمات والمجموعات وقائمة الخدمة الخاصة بك", 
" Create Service Menu":"إنشاء قائمة خدمة", 
"Service Menu name":"اسم قائمة الخدمة", 
"Audit Logs":"سجلات التدقيق", 
"Search Document ID":"معرف وثيقة البحث", 
"Select Users":"حدد المستخدمين", 
"Action - All":"العمل - الكل", 
"Module - All":"الوحدة النمطية - الكل", 
"Last 60 days":"آخر 60 يومًا", 
"Module":"الوحدة النمطية", 
"Action":"فعل", 
"Done by":"فعلت من قبل", 
"Date and Time":"التاريخ والوقت", 
"intellivay":"intellivay", 
"Agency":"وكالة", 
"Updated":"تحديث", 
"AA":"AA", 
"Page Size":"حجم الصفحة", 
"Billing":"الفواتير", 
"LC Communication":"اتصال LC", 
"Location Note":"ملاحظة الموقع", 
"Location Task":"مهمة الموقع", 
"Marketplace":"السوق", 
"Private Integration":"التكامل الخاص", 
"Created":"مخلوق", 
"Deleted":"حذف"
  }

  function smdtr_en_to_ar(i='') {
    if(translation_En_Ar[i]){
      return translation_En_Ar [i]
    }else{
        return i;
    }
  }

    function tSr_En_Ar() {
        const elements = document.body.getElementsByTagName('*');
        for (let i = 0; i < elements.length; i++) {
            let element = elements[i];
            if (element.childNodes.length > 0 && elements[i].tagName !== 'style') {
                element.childNodes.forEach(node => {
                    if (node.nodeType === Node.TEXT_NODE) {
                        node.textContent = smdtr_en_to_ar(node.textContent);
                    }
                });
            }
        }
    }

testload3();
if ( localStorage.getItem("languageSetSS") == 'English' || localStorage.getItem("languageSetSS") == 'عربي' ) {
  sessionStorage.setItem("languageSetSS" , localStorage.getItem("languageSetSS")) ;
}else{
sessionStorage.setItem("languageSetSS", 'English') ;
}

if ( sessionStorage.getItem("languageSetSS") == 'English' || sessionStorage.getItem("languageSetSS") == 'عربي' ) {
// r
} else {
  sessionStorage.setItem("languageSetSS", 'English') ;
}
function testload3(t=0) {
const collection = document.getElementsByClassName("hl-loader-container");
for (let i = 0; i < collection.length; i++) {
  if ( collection[i].style.display == 'none' ) {
  t=1 ;
  var newItem = document.createElement("div");
newItem.innerHTML = `<div class="dbox-lan" id="dbox-lan">
  <button onclick="language_bx4()" class="dropbtn0lan">`+sessionStorage.getItem("languageSetSS")+`</button>
  <div id="language_bx4" class="d-box-co">
    <a style="color:gray" onclick="languageSet('English')">English</a>
    <a style="color:gray" onclick="languageSet('عربي')">عربي</a>
  </div>
</div>`

var list = document.getElementsByClassName("container-fluid")[0];

list.insertBefore(newItem, list.childNodes[0]);
if ( sessionStorage.getItem("languageSetSS") == 'عربي' ) {
tSr_En_Ar();
}

}else{
  if ( sessionStorage.getItem("languageSetSS") == 'عربي' ) {
  tSr_En_Ar();
  }

  
}
}
if ( t==0) {
setTimeout(testload3, 50);
}  else {
  if ( sessionStorage.getItem("languageSetSS") == 'عربي' ) {
  tSr_En_Ar();
  }
setTimeout(testload44, 50);
}

}


function testload44() {
  if ( sessionStorage.getItem("languageSetSS") == 'عربي' ) {
  tSr_En_Ar();
  }
setTimeout(testload44, 100);
}

function language_bx4() {
  document.getElementById("language_bx4").classList.toggle("showDrp");
}
window.onclick = function(event) {
  if ( sessionStorage.getItem("languageSetSS") == 'عربي' ) {
    setTimeout(tSr_En_Ar, 10);
    setTimeout(tSr_En_Ar, 50);
    setTimeout(tSr_En_Ar, 100);
    setTimeout(tSr_En_Ar, 150);
  }


  if (!event.target.matches('.dropbtn0lan')) {
    var dropdowns = document.getElementsByClassName("d-box-co");
    var i;
    for (i = 0; i < dropdowns.length; i++) {
      var openDropdown = dropdowns[i];
      if (openDropdown.classList.contains('showDrp')) {
        openDropdown.classList.remove('showDrp');
      }
    }
  }
}
function languageSet(i) {
sessionStorage.setItem("languageSetSS" , i);
localStorage.setItem("languageSetSS", i);
location.reload();
}
